- hosts: jenkins-user
  become: true
  pre_tasks:
    - name: 'Give jenkins sudoers'
      copy:
        content: |
          jenkins ALL=(ALL:ALL) NOPASSWD:ALL
        dest: /etc/sudoers
        validate: 'visudo -cf %s'
        mode: 0770
  roles:
  - docker_role
  - jenkins_role
  - kubernetes_role

  